image:
  tag: 2.2.0-debug

logLevel: debug

serviceAccount:
  create: true
  name: fluent-bit-sa
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::295387529413:role/production-eks-fluent-bit-irsa"

config:
  inputs: |
    [INPUT]
        Name                tail
        Path                /var/log/containers/*.log
        Tag                 kube.<namespace_name>.<pod_name>.<container_name>
        Tag_Regex           (?<pod_name>[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<namespace_name>[^_]+)_(?<container_name>.+)-
        Skip_Long_Lines     On
        Read_from_Head      True
        multiline.parser    docker, cri

  filters: |
    [FILTER]
        Name kubernetes
        Match kube.trendee.*
        Kube_Tag_Prefix kube.
        Regex_Parser    k8s-custom-tag
        Merge_Log On
        Keep_Log Off
        K8S-Logging.Parser On
        K8S-Logging.Exclude On

    [FILTER]
        Name                grep
        Match               kube.trendee.*
        Exclude             log /.*index.php HTTP.*/
        Exclude             log /\/ HTTP.*/
        Exclude             log /.*ELB-HealthChecker.*/

  outputs: |
    [OUTPUT]
        Name loki
        Match kube.trendee.*
        Host loki-gateway.loki.svc.cluster.local
        Port 80
        auto_kubernetes_labels on

    [OUTPUT]
        Name                         s3
        Match                        kube.trendee.*
        region                       ap-northeast-1
        use_put_object               On
        bucket                       trendee-production-logging
        s3_key_format                /$TAG[1]/%Y-%m-%d/$TAG[2]-%H-%M-%S
        s3_key_format_tag_delimiters .

  customParsers: |
    [PARSER]
        Name     k8s-custom-tag
        Format   regex
        Regex    (?<namespace_name>[^.]+)\.(?<pod_name>[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)\.(?<container_name>[^.]+)$

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "trendee"
    effect: "NoSchedule"
