image:
  tag: 2.2.0-debug

logLevel: debug

serviceAccount:
  create: true
  name: fluent-bit-sa
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::295387529413:role/develop-eks-fluent-bit-irsa"

s3Region: ap-northeast-1

config:
  inputs: |
    [INPUT]
        Name                tail
        Path                /var/log/containers/*.log
        Tag                 kube.<namespace_name>.<pod_name>.<container_name>
        Tag_Regex           (?<pod_name>[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<namespace_name>[^_]+)_(?<container_name>.+)-
        Skip_Long_Lines     On
        Read_from_Head      False
        multiline.parser    docker, cri

  filters: |
    [FILTER]
        Name kubernetes
        Match kube.*
        Kube_Tag_Prefix kube.
        Regex_Parser    k8s-custom-tag
        Merge_Log On
        Keep_Log Off
        K8S-Logging.Parser On
        K8S-Logging.Exclude On

    [FILTER]
        Name                grep
        Match               kube.*
        Exclude             log /.*index.php HTTP.*/
        Exclude             log /.*ELB-HealthChecker.*/

  outputs: |
    [OUTPUT]
        Name                cloudwatch_logs
        Match               kube.ciam-dev.*
        region              {{ .Values.s3Region }}
        log_group_name      /aws/containerinsights/innovation-develop/ciam
        log_stream_prefix   ${HOST_NAME}-
        log_retention_days  30
        auto_create_group   true
        extra_user_agent    container-insights

    [OUTPUT]
        Name loki
        Match kube.*
        Host loki-gateway.grafana.svc.cluster.local
        Port 80
        auto_kubernetes_labels on

  customParsers: |
    [PARSER]
        Name     k8s-custom-tag
        Format   regex
        Regex    (?<namespace_name>[^.]+)\.(?<pod_name>[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)\.(?<container_name>[^.]+)$

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "team-f"
    effect: "NoSchedule"
  - key: "dedicated"
    operator: "Equal"
    value: "magento"
    effect: "NoSchedule"
